cc_library(
    name = "init",
    srcs = ["init.cc"],
    hdrs = ["init.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/log:globals",
        "@abseil-cpp//absl/log:initialize",
    ],
)
