cc_library(
    name = "googletest",
    testonly = True,
    srcs = ["gtest_main.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//rl/util:init",
        "@googletest//:gtest",
    ],
)
